export default {
  /********************* BottomTabs  Icons **********************/
  logo: require('../assets/images/logo.png'),
  goImg: require('../assets/images/goImg.png'),
  homee: require('../assets/images/homee.png'),
  partner: require('../assets/images/partner.png'),
  profile: require('../assets/images/profile.png'),
  tinderr: require('../assets/images/tinderr.png'),
  person: require('../assets/images/person.png'),
  join: require('../assets/images/join.png'),
  name: require('../assets/images/name.png'),
  datingApp: require('../assets/images/datingApp.png'),
  face: require('../assets/images/face.png'),
  addd: require('../assets/images/addd.png'),
  partnerdeets: require('../assets/images/partnerDeets.png'),
  delete: require('../assets/images/delete.png'),
  pen: require('../assets/images/pen.png'),
  quit: require('../assets/images/quit.png'),
  loader1: require('../assets/images/loader1.png'),
  loader2: require('../assets/images/loader2.png'),
  loader3: require('../assets/images/loader3.png'),
  loader4: require('../assets/images/loader4.png'),
  loader5: require('../assets/images/loader5.png'),
  loader6: require('../assets/images/loader6.png'),
  reverseLoader: require('../assets/images/reverseLoader.json'),
  review: require('../assets/images/review.png'),
  user: require('../assets/images/user.png'),
  search: require('../assets/images/Search.png'),
};
